config/routes.rb
Rails.application.routes.draw do
  resources :fireworks
  devise_for :users
  root to: "fireworks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/firework.rb
class Firework < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fireworks_controller.rb
class FireworksController < ApplicationController
  before_action :set_firework, only: [:show, :edit, :update, :destroy]

  # GET /fireworks
  # GET /fireworks.json
  def index
    @fireworks = Firework.all
  end

  # GET /fireworks/1
  # GET /fireworks/1.json
  def show
  end

  # GET /fireworks/new
  def new
    @firework = Firework.new
  end

  # GET /fireworks/1/edit
  def edit
  end

  # POST /fireworks
  # POST /fireworks.json
  def create
    @firework = Firework.new(firework_params)

    respond_to do |format|
      if @firework.save
        format.html { redirect_to @firework, notice: 'Firework was successfully created.' }
        format.json { render :show, status: :created, location: @firework }
      else
        format.html { render :new }
        format.json { render json: @firework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fireworks/1
  # PATCH/PUT /fireworks/1.json
  def update
    respond_to do |format|
      if @firework.update(firework_params)
        format.html { redirect_to @firework, notice: 'Firework was successfully updated.' }
        format.json { render :show, status: :ok, location: @firework }
      else
        format.html { render :edit }
        format.json { render json: @firework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fireworks/1
  # DELETE /fireworks/1.json
  def destroy
    @firework.destroy
    respond_to do |format|
      format.html { redirect_to fireworks_url, notice: 'Firework was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_firework
      @firework = Firework.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def firework_params
      params.require(:firework).permit(:name, :style, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fireworks_helper.rb
module FireworksHelper
end

app/views/fireworks/_form.html.erb
<%= form_with(model: firework, local: true) do |form| %>
  <% if firework.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(firework.errors.count, "error") %> prohibited this firework from being saved:</h2>

      <ul>
        <% firework.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <%= form.text_field :style %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fireworks/edit.html.erb
<h1>Editing Firework</h1>

<%= render 'form', firework: @firework %>

<%= link_to 'Show', @firework %> |
<%= link_to 'Back', fireworks_path %>

app/views/fireworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fireworks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Style</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fireworks.each do |firework| %>
      <tr>
        <td><%= firework.name %></td>
        <td><%= firework.style %></td>
        <td><%= firework.description %></td>
        <td><%= link_to 'Show', firework %></td>
        <td><%= link_to 'Edit', edit_firework_path(firework) %></td>
        <td><%= link_to 'Destroy', firework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Firework', new_firework_path %>

app/views/fireworks/new.html.erb
<h1>New Firework</h1>

<%= render 'form', firework: @firework %>

<%= link_to 'Back', fireworks_path %>

app/views/fireworks/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @firework.name %>
</p>

<p>
  <strong>Style:</strong>
  <%= @firework.style %>
</p>

<p>
  <strong>Description:</strong>
  <%= @firework.description %>
</p>

<%= link_to 'Edit', edit_firework_path(@firework) %> |
<%= link_to 'Back', fireworks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fireworksapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </form>
  </div>
</nav>